public class Maths_Operations {
 public double num1 = 86;
  public double num2 = 49;
  public double result;
    
    public void Addition()
    {
        result = num1+num2;
        system.debug('Addition of two numbers is: '+result);
    }
    
    public void substraction()
    {
        result = num1-num2;
        system.debug('substraction of two numbers is: '+result);
    }
    
    public void Multiplication()
    {
        result = num1*num2;
        system.debug('Multiplication of two numbers is: '+result);
    }
    
    public void Division()
    {
        result = num1/num2;
        system.debug('Division of two numbers is: '+result);
    }
}