public class Sample_greatestnumber {
/*public integer num1=100;
    public integer num2=123;
    //with argument
 public void display(integer num1, integer num2)
 {
    if(num1>num2)
    {
        system.debug('greatest num is '+num1);
    }
     else
     {
         system.debug('greatest num is '+num2);
     }
 }*/
    public Sample_greatestnumber(integer num1, integer num2)
    {
          if(num1>num2)
    {
        system.debug('greatest num is '+num1);
    }
     else
     {
         system.debug('greatest num is '+num2);
     }
    }
}